version: "3"

services:
  orderer:
    image: hyperledger/fabric-orderer:2.2.3
    container_name: orderer.482.solutions
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./orderer_data:/etc/hyperledger/fabric
    ports:
      - 7050:7050
    command: orderer
    networks:
      hlf2:
         ipv4_address: 172.28.0.5

networks:
  hlf2:
    external: true