version: "3"

services:
  # This database is not intended to be exposed to any outer network, so the
  # default user and password are left as is. For the same reason there is no
  # ssl.
  db:
    image: postgres:11.5
    container_name: postgres_ca.482.solutions
    environment:
      - POSTGRES_DB=fabric_ca
    volumes:
      - postgres_ca.482.solutions:/var/lib/postgresql/data
    networks:
      hlf2:
        ipv4_address: 172.28.0.2

  ca:
    image: hyperledger/fabric-ca:1.4
    container_name: ca.482.solutions
    depends_on:
      - db
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - ./ca_data:/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054
    command: sh -c "sleep 5 && fabric-ca-server start"
    networks:
      hlf2:
        ipv4_address: 172.28.0.3


volumes:
  postgres_ca.482.solutions:
networks:
  hlf2:
    external: true