NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/172-28-0-3-7054.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/172-28-0-3-7054.pem
    OrganizationalUnitIdentifier: peer
  OrdererOUIdentifier:
    Certificate: cacerts/172-28-0-3-7054.pem
    OrganizationalUnitIdentifier: peer
