NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-482-solutions-7054.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-482-solutions-7054.pem
    OrganizationalUnitIdentifier: peer
  OrdererOUIdentifier:
    Certificate: cacerts/ca-482-solutions-7054.pem
    OrganizationalUnitIdentifier: orderer
