# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---

Organizations:
    - &482solutions
        Name: 482solutionsMSP
        ID: 482solutionsMSP
        MSPDir: peer/msp
        Policies: &482solutionsPolicies
            Readers:
                Type: Signature
                Rule: "OR('482solutionsMSP.client', '482solutionsMSP.peer', '482solutionsMSP.admin')"
            Writers:
                Type: Signature
                Rule: "OR('482solutionsMSP.client', '482solutionsMSP.admin')"
            Admins:
                Type: Signature
                Rule: "OR('482solutionsMSP.admin')"            
            Endorsement:
                Type: Signature
                Rule: "OR('482solutionsMSP.peer')"


Application: &ApplicationDefaults
    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Organizations:

Capabilities:
    Application: &ApplicationCapabilities
        V1_4_2: true


Profiles:
    TestChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *482solutions
            Capabilities:
                <<: *ApplicationCapabilities