---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ./orderer/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - orderer.482.solutions:7050
    - &482solutionsOrg
        Name: 482solutionsOrg
        ID: 482solutionsMSP
        MSPDir: ./peer/msp
        Policies: &482solutionsPolicies
            Readers:
                Type: Signature
                Rule: "OR('482solutionsMSP.client', '482solutionsMSP.peer', '482solutionsMSP.admin')"
            Writers:
                Type: Signature
                Rule: "OR('482solutionsMSP.client', '482solutionsMSP.admin')"
            Admins:
                Type: Signature
                Rule: "OR('482solutionsMSP.client', '482solutionsMSP.peer', '482solutionsMSP.admin')"        
            Endorsement:
                Type: Signature
                Rule: "OR('482solutionsMSP.peer')"


Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true


### Orderer: &OrdererDefaults
###     OrdererType: etcdraft
###     Addresses:
###         - orderer.482.solutions:7050
###     EtcdRaft:
###         Consenters:
###         - Host: orderer.482.solutions
###           Port: 7050
###           ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
###           ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
###     BatchTimeout: 2s
###     BatchSize:
###         MaxMessageCount: 10
###         AbsoluteMaxBytes: 99 MB
###         PreferredMaxBytes: 512 KB
###     Organizations:
###     Policies:
###         Readers:
###             Type: ImplicitMeta
###             Rule: "ANY Readers"
###         Writers:
###             Type: ImplicitMeta
###             Rule: "ANY Writers"
###         Admins:
###             Type: ImplicitMeta
###             Rule: "MAJORITY Admins"
###         BlockValidation:
###             Type: ImplicitMeta
###             Rule: "ANY Writers"
### 

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
    BatchTimeout: 400ms
    BatchSize:
        MaxMessageCount: 50
        AbsoluteMaxBytes: 1 MB
        PreferredMaxBytes: 1 MB
    MaxChannels: 0
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities
        
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
    Capabilities:
        <<: *ChannelCapabilities


Application: &ApplicationDefaults
    Policies: &ApplicationPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
    Organizations:


# Capabilities:
#     Application: &ApplicationCapabilities
#         V2_0: true


Profiles:
    OrgOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *482solutionsOrg
    TestChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *482solutionsOrg
            Capabilities:
                <<: *ApplicationCapabilities
            Policies:
                <<: *ApplicationPolicies
                Admins:
                    Type: Signature
                    Rule: "OR('482solutionsOrg.member')"
###
###
###    SampleSingleMSPSolo:
###        <<: *ChannelDefaults
###        Orderer:
###            <<: *OrdererDefaults
###            Addresses:
###                - 172.28.0.5:7050
###            Organizations:
###                - *482solutions        
###        Consortiums:
###            SampleConsortium:
###                Organizations:
###                    - *482solutions
###
###